-- AlterTable
ALTER TABLE `detection_logs` 
ADD COLUMN `metrics` JSON NULL,
ADD COLUMN `report` TEXT NULL,
ADD COLUMN `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
